
[build]
publish = "./public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.74.3"
HUGO_BASEURL = "/"

[[pluginsss]]
package = "/plugins/directustest"

[[pluginsss]]
 package = "@netlify/plugin-local-install-core"
